### ISSUE TITLE
`while` throws error if first command

### ISSUE THREAD

**Issue by ma11hew28** [73rhodes/sideflow#1]
If `while` is the first command of a test case, Selenium throws an "Invalid row_num specified" error. I also [reported this issue on a fork](https://github.com/davehunt/selenium-ide-flowcontrol/issues#issue/1).

**Comment by XtinaSchelin** [comment]
I can reproduce this now. Mac 10.10.5, Firefox 40.0.3, Selenium IDE 2.9.0. When a while command is the first command in a test case, I receive this error:

[error] Unexpected Exception: Error: Invalid row_num specified..

When I put a simple store command right above it, it works fine.
