### ISSUE TITLE
sideflow.js for selenium-html-runner

### ISSUE THREAD

**Issue by antonpiks** [73rhodes/sideflow#13]
Hello. It is more a question, rather than an issue, but I would like to use this plugin for selenium-html-runner as user-extension. Currently, it ignores this extension, so all the exported test-cases are not working with this runner. Can you please tell me is there a way to modify this in order to make it compatible with html runner?
Thanks in advance...

**Comment by 73rhodes** [comment]
It could be ported, but this extension only works with Selenium IDE.
